# Generated by Django 3.0 on 2019-12-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=600),
        ),
    ]
