# Generated by Django 3.0 on 2019-12-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0002_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact_info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
